# The following patch makes AWSClusterController CRD a "singleton".
# Only one CR can be created because validation restricts the value of name.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: awsclustercontrollerprincipals.infrastructure.cluster.x-k8s.io

#spec:
##  validation:
##    openAPIV3Schema:
##      properties:
##        metadata:
##          properties:
##            name:
##              type: string
##              pattern: "default"

#  versions:
#  - name: v1alpha3
#    schema:
#      openAPIV3Schema:
#        properties:
#         metadata:
#          name:
#            pattern: "default"
#            type: string
#
spec:
  versions:
    - name: v1alpha3
      schema:
        openAPIV3Schema:
          properties:
            metadata:
              properties:
                name:
                  pattern: default
                  type: string
              type: object