# The following patch makes AWSClusterController CRD a "singleton".
# Only one CR can be created because validation restricts the value of name.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: awsclustercontrollerprincipals.infrastructure.cluster.x-k8s.io
spec:
  validation:
    openAPIV3Schema:
      properties:
        metadata:
          properties:
            name:
              type: string
              pattern: "default"
